### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by carrgilson** [obergt/Isilon_Tools#3]
I'm unable to run a backup, I get the following output:

```
# python /opt/Isilon_Tools/isi_tools.py backup --type exports --user myusername --password mypassword --name isilon.dns.address
/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/opt/Isilon_Tools/isi_tools.py", line 147, in <module>
    main()
  File "/opt/Isilon_Tools/isi_tools.py", line 141, in main
    backup(api, args)
  File "/opt/Isilon_Tools/isi_tools.py", line 61, in backup
    objects = api.platform.get_object(args.type)
  File "/opt/Isilon_Tools/isilon/platform.py", line 55, in get_object
    r = self.api_call("GET", self.platform_url + "/protocols/nfs/exports?zone="+zone[1])
TypeError: 'int' object has no attribute '__getitem__'
```

I'm running on Python 2.7.5 against both OneFS 7.1.1.2 and 7.2.0.1

**Comment by obergt** [comment]
Fixed!
I Just uploaded new version..

**Comment by carrgilson** [comment]
Yep! That's working for me now.
